adminUser:
  password: vault:jx-infra-staging/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  token: vault:jx-infra-staging/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-infra-staging/prow:hmacToken
